In [19]:
import coderdata as cd

In [20]:
cd.download(name='ccle', local_path='../data/Cancer/coderdata/')

Downloaded 'https://ndownloader.figshare.com/files/51830555' to '../data/Cancer/coderdata/ccle_proteomics.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830558' to '../data/Cancer/coderdata/ccle_mutations.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830591' to '../data/Cancer/coderdata/ccle_copy_number.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830627' to '../data/Cancer/coderdata/ccle_experiments.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830654' to '../data/Cancer/coderdata/ccle_transcriptomics.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830669' to '../data/Cancer/coderdata/ccle_drugs.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830726' to '../data/Cancer/coderdata/ccle_samples.csv'
Downloaded 'https://ndownloader.figshare.com/files/51830741' to '../data/Cancer/coderdata/ccle_drug_descriptors.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51966266' to '../data/Cancer/coderdata/genes.csv.gz'

In [21]:
ccle = cd.load(name='ccle', local_path='../data/Cancer/coderdata/')

Importing raw data ...
DONErting 'copy_number' from ../data/Cancer/coderdata/ccle_copy_number.csv.gz ...
DONErting 'mutations' from ../data/Cancer/coderdata/ccle_mutations.csv.gz ...
Importing 'genes' from ../data/Cancer/coderdata/genes.csv.gz ... DONE
DONErting 'proteomics' from ../data/Cancer/coderdata/ccle_proteomics.csv.gz ...
Importing 'drugs' from ../data/Cancer/coderdata/ccle_drugs.tsv.gz ... DONE
Importing 'drug_descriptors' from ../data/Cancer/coderdata/ccle_drug_descriptors.tsv.gz ... DONE
DONErting 'transcriptomics' from ../data/Cancer/coderdata/ccle_transcriptomics.csv.gz ...
Importing 'experiments' from ../data/Cancer/coderdata/ccle_experiments.tsv.gz ... DONE
Importing 'samples' from ../data/Cancer/coderdata/ccle_samples.csv ... DONE
Importing raw data ... DONE

In [22]:
ccle.types()

['transcriptomics',
 'proteomics',
 'mutations',
 'copy_number',
 'samples',
 'drugs',
 'experiments',
 'genes']

In [23]:
ccle.experiments

,source,improve_sample_id,improve_drug_id,study,time,time_unit,dose_response_metric,dose_response_value
0,pharmacoGX,1.0,SMI_10282,CCLE,72,hours,fit_auc,0.9356
1,pharmacoGX,1.0,SMI_10376,CCLE,72,hours,fit_auc,0.8343
2,pharmacoGX,1.0,SMI_11509,CCLE,72,hours,fit_auc,0.6818
3,pharmacoGX,1.0,SMI_12635,CCLE,72,hours,fit_auc,0.6368
4,pharmacoGX,1.0,SMI_20869,CCLE,72,hours,fit_auc,0.7757
...,...,...,...,...,...,...,...,...
115655,pharmacoGX,1929.0,SMI_55576,CCLE,72,hours,dss,0.1964
115656,pharmacoGX,1929.0,SMI_55606,CCLE,72,hours,dss,0.0000
115657,pharmacoGX,1929.0,SMI_56571,CCLE,72,hours,dss,0.0000
115658,pharmacoGX,1929.0,SMI_659,CCLE,72,hours,dss,0.0000
115659,pharmacoGX,1929.0,SMI_7971,CCLE,72,hours,dss,0.0000

In [24]:
ccle.format(data_type='transcriptomics')

entrez_id,1,2,9,10,12,13,14,15,16,18,...,115253422,116033993,118142757,118568804,122394733,122405565,124905743,125316803,127898561,128854680
improve_sample_id,,,,,,,,,,,,,,,,,,,,,
1,0.377908,0.214517,10.884808,1.004783,0.374231,5.125926,58.706594,0.178292,182.080289,4.410450,...,1.937344,0.0,0.128292,0.0,0.540773,2.314544,0.0,21.933752,10.997310,0.269329
4,0.068752,0.497908,14.466601,0.090195,0.329962,0.665773,89.898180,0.366517,119.751112,0.462088,...,2.513491,0.0,0.007178,0.0,1.978817,34.059067,0.0,31.096575,23.478747,0.000000
9,1.875525,0.307414,3.210817,0.000000,0.042032,0.048292,89.053021,0.075516,177.328384,0.102164,...,1.933573,0.0,0.000000,0.0,1.934707,45.165385,0.0,23.882962,34.018946,0.027178
10,0.055516,0.109517,3.116322,0.075000,0.215269,0.043292,52.793034,1.587481,48.576951,1.509450,...,2.589763,0.0,0.000000,0.0,2.093848,12.893512,0.0,28.347959,19.850747,0.261517
12,2.236951,0.118161,7.671384,0.000000,0.088161,0.000000,60.404582,0.852656,129.955312,4.494119,...,2.066950,0.0,0.015000,0.0,3.142531,1.096749,0.0,27.788301,30.176804,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1919,1.841711,0.083805,5.067848,0.000000,0.119393,0.000000,51.130153,3.460516,140.601954,0.731998,...,2.220330,0.0,0.042178,0.0,3.465080,0.953505,0.0,50.997643,42.976158,0.000000
1921,1.367750,60.166851,4.795926,1.116233,1.118805,2.972241,67.159499,0.567414,124.876073,20.823071,...,1.839960,0.0,0.000000,0.0,0.042032,28.611804,0.0,30.884286,34.351122,0.179517
1924,4.401903,0.137504,2.467279,0.000000,0.773996,0.084064,5.927659,1.049631,7.447001,1.655352,...,1.687061,0.0,0.000000,0.0,3.727920,1.220330,0.0,5.210233,5.020147,0.000000
1925,2.216196,0.233161,5.891079,0.000000,0.042032,0.000000,56.024912,0.454393,107.634286,3.782531,...,1.618239,0.0,0.000000,0.0,6.657481,8.408676,0.0,27.351329,24.425200,0.220280
1929,0.333424,0.124328,2.140779,1.257011,0.097611,0.124328,6.752347,0.214125,5.329124,4.441616,...,1.709291,0.0,0.014355,0.0,2.584963,3.232661,0.0,5.311430,4.408712,0.000000

In [25]:
cd.download(name='ctrpv2', local_path='../data/Cancer/coderdata/')

Downloaded 'https://ndownloader.figshare.com/files/51830561' to '../data/Cancer/coderdata/ctrpv2_experiments.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830564' to '../data/Cancer/coderdata/ctrpv2_transcriptomics.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830642' to '../data/Cancer/coderdata/ctrpv2_proteomics.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830645' to '../data/Cancer/coderdata/ctrpv2_drug_descriptors.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830696' to '../data/Cancer/coderdata/ctrpv2_samples.csv'
Downloaded 'https://ndownloader.figshare.com/files/51830744' to '../data/Cancer/coderdata/ctrpv2_copy_number.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830792' to '../data/Cancer/coderdata/ctrpv2_mutations.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830924' to '../data/Cancer/coderdata/ctrpv2_drugs.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51966266' to '../data/Cancer/coderdata/genes.csv.gz'

In [26]:
ctrpv2 = cd.load(name='ctrpv2', local_path='../data/Cancer/coderdata/')

Importing raw data ...
DONErting 'experiments' from ../data/Cancer/coderdata/ctrpv2_experiments.tsv.gz ...
Importing 'samples' from ../data/Cancer/coderdata/ctrpv2_samples.csv ... DONE
DONErting 'proteomics' from ../data/Cancer/coderdata/ctrpv2_proteomics.csv.gz ...
DONErting 'transcriptomics' from ../data/Cancer/coderdata/ctrpv2_transcriptomics.csv.gz ...
DONErting 'copy_number' from ../data/Cancer/coderdata/ctrpv2_copy_number.csv.gz ...
Importing 'drugs' from ../data/Cancer/coderdata/ctrpv2_drugs.tsv.gz ... DONE
DONErting 'mutations' from ../data/Cancer/coderdata/ctrpv2_mutations.csv.gz ...
Importing 'genes' from ../data/Cancer/coderdata/genes.csv.gz ... DONE
DONErting 'drug_descriptors' from ../data/Cancer/coderdata/ctrpv2_drug_descriptors.tsv.gz ...
Importing raw data ... DONE

In [28]:
ctrpv2.types()

['transcriptomics',
 'proteomics',
 'mutations',
 'copy_number',
 'samples',
 'drugs',
 'experiments',
 'genes']

In [29]:
ctrpv2.transcriptomics

,entrez_id,improve_sample_id,transcriptomics,source,study
0,7105,137,4.331992,Broad,DepMap
1,64102,137,0.000000,Broad,DepMap
2,8813,137,7.364660,Broad,DepMap
3,6359,137,2.792855,Broad,DepMap
4,57147,137,2.792855,Broad,DepMap
...,...,...,...,...,...
31876845,100130705,115,1.330000,Broad,Sanger & Broad Cell Lines RNASeq
31876846,100130705,1562,0.650000,Broad,Sanger & Broad Cell Lines RNASeq
31876847,100130705,1485,2.140000,Broad,Sanger & Broad Cell Lines RNASeq
31876848,100130705,1552,3.550000,Broad,Sanger & Broad Cell Lines RNASeq
31876849,100130705,1605,1.200000,Broad,Sanger & Broad Cell Lines RNASeq

In [44]:
ctrpv2.transcriptomics[ctrpv2.transcriptomics["improve_sample_id"]==1485]["transcriptomics"].sum()

578890.9500000001

In [30]:
ctrpv2.proteomics

         entrez_id  proteomics  improve_sample_id   study source
0             6558    2.111348                590  DepMap  Broad
1            23028    0.379683                590  DepMap  Broad
2             6657   -0.246367                590  DepMap  Broad
3             5396    0.322445                590  DepMap  Broad
4            51450   -0.246657                590  DepMap  Broad
...            ...         ...                ...     ...    ...
3400581      10945   -1.047530                979  DepMap  Broad
3400582     153339    1.011594                979  DepMap  Broad
3400583        241    0.640295                979  DepMap  Broad
3400584      84418   -2.004067                979  DepMap  Broad
3400585      29097    0.094595                979  DepMap  Broad

[3400586 rows x 5 columns]

In [31]:
ctrpv2.mutations

,entrez_id,improve_sample_id,mutation,variant_classification,source,study
0,388581,1014,c.780_781GC>AG,Missense_Mutation,Broad,DepMap
1,54897,1014,c.3329T>C,Missense_Mutation,Broad,DepMap
2,54897,1014,c.3201A>C,Silent,Broad,DepMap
3,400736,1014,c.770C>T,Missense_Mutation,Broad,DepMap
4,391003,1014,c.653T>C,Missense_Mutation,Broad,DepMap
...,...,...,...,...,...,...
1580708,29119,1764,-,Intron,Broad,Sanger
1580709,288,1764,c.4403G>A,Missense_Mutation,Broad,Sanger
1580710,288,1764,-,Intron,Broad,Sanger
1580711,80114,1764,-,Intron,Broad,Sanger
1580712,7321,1764,c.?,3'UTR,Broad,Sanger

In [32]:
ctrpv2.copy_number

          entrez_id  improve_sample_id   copy_number copy_call source   study
0             79501                 31  3.880916e-08  deep del  Broad  DepMap
1             81099                 31  3.880916e-08  deep del  Broad  DepMap
2            729759                 31  1.417715e+00      gain  Broad  DepMap
3             81399                 31  1.417715e+00      gain  Broad  DepMap
4            148398                 31  1.417715e+00      gain  Broad  DepMap
...             ...                ...           ...       ...    ...     ...
16721100      57054               1181  8.545036e-02  deep del  Broad  DepMap
16721101      57135               1181  8.545036e-02  deep del  Broad  DepMap
16721102     442868               1181  8.545036e-02  deep del  Broad  DepMap
16721103       9085               1181  1.156591e-01  deep del  Broad  DepMap
16721104     548644               1181  8.614649e-01   diploid  Broad  DepMap

[16721105 rows x 6 columns]

In [33]:
ctrpv2.samples

,common_name,cancer_type,other_names,species,improve_sample_id,other_id_source,other_id,model_type
0,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,PatientID,PT-GiBvWu,cell line
1,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,DepMap,ACH-000205,cell line
2,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,Sanger,SIDM01774,cell line
3,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,CCLE,PK59_PANCREAS,cell line
4,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,Cellosaurus,CVCL_4897,cell line
...,...,...,...,...,...,...,...,...
21673,COLO-320-HSR,Colon Adenocarcinoma,Colorado 320 Homogeneously Staining Regions,Homo sapiens (Human),752,DepMap,ACH-002219,cell line
21674,COLO-320-HSR,Colon Adenocarcinoma,Colorado 320 Homogeneously Staining Regions,Homo sapiens (Human),752,Sanger,SIDM00842,cell line
21675,COLO-320-HSR,Colon Adenocarcinoma,Colorado 320 Homogeneously Staining Regions,Homo sapiens (Human),752,CCLE,COLO320HSR_LARGE_INTESTINE,cell line
21676,COLO-320-HSR,Colon Adenocarcinoma,Colorado 320 Homogeneously Staining Regions,Homo sapiens (Human),752,COSMIC,910569,cell line
21677,COLO-320-HSR,Colon Adenocarcinoma,Colorado 320 Homogeneously Staining Regions,Homo sapiens (Human),752,Cellosaurus,CVCL_0220,cell line

In [34]:
ctrpv2.drugs

,improve_drug_id,chem_name,pubchem_id,canSMILES,InChIKey,formula,weight
0,SMI_85,4-08-00-03754 (beilstein handbook reference),3503,CC1=CC2=C(C(=C(C(=C2C(C)C)O)O)C=O)C(=C1C3=C(C4...,QBKSWRVVCFFDOT-UHFFFAOYSA-N,C30H30O8,518.6
1,SMI_85,cas-303-45-7,3503,CC1=CC2=C(C(=C(C(=C2C(C)C)O)O)C=O)C(=C1C3=C(C4...,QBKSWRVVCFFDOT-UHFFFAOYSA-N,C30H30O8,518.6
2,SMI_85,ncgc00016423-12,3503,CC1=CC2=C(C(=C(C(=C2C(C)C)O)O)C=O)C(=C1C3=C(C4...,QBKSWRVVCFFDOT-UHFFFAOYSA-N,C30H30O8,518.6
3,SMI_85,db13044,3503,CC1=CC2=C(C(=C(C(=C2C(C)C)O)O)C=O)C(=C1C3=C(C4...,QBKSWRVVCFFDOT-UHFFFAOYSA-N,C30H30O8,518.6
4,SMI_85,no fertil,3503,CC1=CC2=C(C(=C(C(=C2C(C)C)O)O)C=O)C(=C1C3=C(C4...,QBKSWRVVCFFDOT-UHFFFAOYSA-N,C30H30O8,518.6
...,...,...,...,...,...,...,...
31077,SMI_55542,"(s)-14-methyl-8,13,13b,14-tetrahydroindolo[2',...",442088,CN1C2C3=C(CCN2C(=O)C4=CC=CC=C41)C5=CC=CC=C5N3,TXDUTHBFYKGSAH-SFHVURJKSA-N,C19H17N3O,303.4
31078,SMI_55542,"indol(2',3':3,4)pyrido(2,1-b)quinazolin-5(7h)-...",442088,CN1C2C3=C(CCN2C(=O)C4=CC=CC=C41)C5=CC=CC=C5N3,TXDUTHBFYKGSAH-SFHVURJKSA-N,C19H17N3O,303.4
31079,SMI_55542,d-evodiamine,442088,CN1C2C3=C(CCN2C(=O)C4=CC=CC=C41)C5=CC=CC=C5N3,TXDUTHBFYKGSAH-SFHVURJKSA-N,C19H17N3O,303.4
31080,SMI_55542,q-100579,442088,CN1C2C3=C(CCN2C(=O)C4=CC=CC=C41)C5=CC=CC=C5N3,TXDUTHBFYKGSAH-SFHVURJKSA-N,C19H17N3O,303.4
31081,SMI_55542,evodiamine (standard),442088,CN1C2C3=C(CCN2C(=O)C4=CC=CC=C41)C5=CC=CC=C5N3,TXDUTHBFYKGSAH-SFHVURJKSA-N,C19H17N3O,303.4

In [35]:
ctrpv2.experiments

,source,improve_sample_id,improve_drug_id,study,time,time_unit,dose_response_metric,dose_response_value
0,pharmacoGX,1.0,SMI_10067,CTRPv2,72,hours,fit_auc,0.5965
1,pharmacoGX,1.0,SMI_10110,CTRPv2,72,hours,fit_auc,0.8377
2,pharmacoGX,1.0,SMI_10143,CTRPv2,72,hours,fit_auc,0.8027
3,pharmacoGX,1.0,SMI_10197,CTRPv2,72,hours,fit_auc,0.9995
4,pharmacoGX,1.0,SMI_10282,CTRPv2,72,hours,fit_auc,0.8495
...,...,...,...,...,...,...,...,...
3109575,pharmacoGX,1929.0,SMI_8071,CTRPv2,72,hours,dss,0.2317
3109576,pharmacoGX,1929.0,SMI_8294,CTRPv2,72,hours,dss,0.2681
3109577,pharmacoGX,1929.0,SMI_8489,CTRPv2,72,hours,dss,0.0000
3109578,pharmacoGX,1929.0,SMI_85,CTRPv2,72,hours,dss,0.1403
3109579,pharmacoGX,1929.0,SMI_8988,CTRPv2,72,hours,dss,0.1406

In [36]:
ctrpv2.genes

        entrez_id         other_id   gene_symbol     other_id_source
0               1              A1B          A1BG        entrez_alias
1               1              ABG          A1BG        entrez_alias
2               1              GAB          A1BG        entrez_alias
3               1         HYST2477          A1BG        entrez_alias
4               1             A1BG          A1BG        entrez_alias
...           ...              ...           ...                 ...
134505  131675794  ENST00000632371        NPIPA6  ensembl_transcript
134506  131675794  ENST00000620107        NPIPA6  ensembl_transcript
134507  131675794  ENST00000617392        NPIPA6  ensembl_transcript
134508  131768270  ENST00000715596  LOC131768270  ensembl_transcript
134509  131768270  ENST00000715679  LOC131768270  ensembl_transcript

[134510 rows x 4 columns]

In [1]:
import pandas as pd
import numpy as np
import coderdata as cd
# import keras
from numpy import loadtxt
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from rdkit import Chem
from rdkit.Chem import AllChem
# from keras.models import Model
# from keras.layers import Input, Dense, concatenate
# from keras.optimizers import Adam
# from keras.losses import MeanSquaredError
# from keras.metrics import MeanAbsoluteError
# from keras import layers
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
# cd.download(name='beataml',  local_path='../data/Cancer/coderdata/')
beataml = cd.load(name="beataml", local_path='../data/Cancer/coderdata/')

Importing raw data ...
Importing 'drugs' from ../data/Cancer/coderdata/beataml_drugs.tsv.gz ... DONE
DONErting 'transcriptomics' from ../data/Cancer/coderdata/beataml_transcriptomics.csv.gz ...
Importing 'genes' from ../data/Cancer/coderdata/genes.csv.gz ... DONE
Importing 'mutations' from ../data/Cancer/coderdata/beataml_mutations.csv.gz ... DONE
DONErting 'drug_descriptors' from ../data/Cancer/coderdata/beataml_drug_descriptors.tsv.gz ...
Importing 'samples' from ../data/Cancer/coderdata/beataml_samples.csv ... DONE
Importing 'experiments' from ../data/Cancer/coderdata/beataml_experiments.tsv.gz ... DONE
DONErting 'proteomics' from ../data/Cancer/coderdata/beataml_proteomics.csv.gz ...
Importing raw data ... DONE

In [3]:
beataml.types()

['transcriptomics',
 'proteomics',
 'mutations',
 'samples',
 'drugs',
 'experiments',
 'genes']

In [4]:
beataml.drugs

,improve_drug_id,chem_name,pubchem_id,formula,weight,InChIKey,canSMILES
0,SMI_43282,cytarabine,6253.0,C9H13N3O5,243.22,UHDGCWIWMRVCDJ-CCXZUQQUSA-N,C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O
1,SMI_23975,entospletinib,59473233.0,C23H21N7O,411.50,XSMSNFMDVXXHGJ-UHFFFAOYSA-N,C1COCCN1C2=CC=C(C=C2)NC3=NC(=CN4C3=NC=C4)C5=CC...
2,SMI_10282,nutlin 3a,11433190.0,C30H30Cl2N4O4,581.50,BDUHCSBCVGXTJM-WUFINQPMSA-N,CC(C)OC1=C(C=CC(=C1)OC)C2=NC(C(N2C(=O)N3CCNC(=...
3,SMI_56581,akt inhibitor iv,5719375.0,C31H27IN4S,614.50,NAYRELMNTQSBIN-UHFFFAOYSA-M,CC[N+]1=C(N(C2=C1C=C(C=C2)C3=NC4=CC=CC=C4S3)C5...
4,SMI_56572,akt inhibitor x,16760284.0,C20H26Cl2N2O,381.30,SVKSJUIYYCQZEC-UHFFFAOYSA-N,CCN(CC)CCCCN1C2=CC=CC=C2OC3=C1C=C(C=C3)Cl.Cl
...,...,...,...,...,...,...,...
161,SMI_2955,ralimetinib,11539025.0,C24H29FN6,420.50,XPPBBJCBDOEXDN-UHFFFAOYSA-N,CC(C)(C)CN1C2=C(C=CC(=N2)C3=C(N=C(N3)C(C)(C)C)...
162,SMI_56589,ranolazine,56959.0,C24H33N3O4,427.50,XKLMZUWKNUAPSZ-UHFFFAOYSA-N,CC1=C(C(=CC=C1)C)NC(=O)CN2CCN(CC2)CC(COC3=CC=C...
163,SMI_56573,xmd 8-87,53322923.0,C24H27N7O2,445.50,LGLHCXISMKHLIK-UHFFFAOYSA-N,CN1CCN(CC1)C2=CC(=C(C=C2)NC3=NC=C4C(=N3)N(C5=C...
164,SMI_39543,bms-754807,24785538.0,C23H24FN9O,461.50,LQVXSNNAFNGRAH-QHCPKHFHSA-N,CC1(CCCN1C2=NN3C=CC=C3C(=N2)NC4=NNC(=C4)C5CC5)...
165,SMI_5202,everolimus,6442177.0,C53H83NO14,958.20,HKVAMNSJSFKALM-GKUWKFKPSA-N,CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)C...

In [5]:
beataml.experiments

,source,improve_sample_id,improve_drug_id,study,time,time_unit,dose_response_metric,dose_response_value
0,synapse,3909,SMI_11493,BeatAML,72,hrs,fit_auc,0.4916
1,synapse,3909,SMI_11502,BeatAML,72,hrs,fit_auc,0.8310
2,synapse,3909,SMI_11509,BeatAML,72,hrs,fit_auc,0.3593
3,synapse,3909,SMI_13100,BeatAML,72,hrs,fit_auc,0.7340
4,synapse,3909,SMI_14356,BeatAML,72,hrs,fit_auc,0.8563
...,...,...,...,...,...,...,...,...
236615,synapse,3628,SMI_6419,BeatAML,72,hrs,dss,0.0000
236616,synapse,3628,SMI_659,BeatAML,72,hrs,dss,0.2450
236617,synapse,3628,SMI_7473,BeatAML,72,hrs,dss,0.0000
236618,synapse,3628,SMI_7971,BeatAML,72,hrs,dss,0.0000
236619,synapse,3628,SMI_8098,BeatAML,72,hrs,dss,0.2152

In [6]:
merged_df = pd.merge(beataml.experiments[beataml.experiments["dose_response_metric"] == "fit_auc"][['improve_sample_id', 'improve_drug_id', 'dose_response_value']],
                     beataml.drugs[['improve_drug_id', 'canSMILES']],
                     on='improve_drug_id',
                     how='inner').drop_duplicates()
merged_df = merged_df.dropna(subset=['canSMILES'])
merged_df

,improve_sample_id,improve_drug_id,dose_response_value,canSMILES
0,3909,SMI_11493,0.4916,CCN1C2=C(C(=NC=C2OCC3CCCNC3)C#CC(C)(C)O)N=C1C4...
1,3909,SMI_11502,0.8310,CS(=O)(=O)N1CCN(CC1)CC2=CC3=C(S2)C(=NC(=N3)C4=...
2,3909,SMI_11509,0.3593,CC(C)S(=O)(=O)C1=CC=CC=C1NC2=NC(=NC=C2Cl)NC3=C...
3,3909,SMI_13100,0.7340,COC1=CC=C(C=C1)COC2=C(C=C(C=C2)CC3=CN=C(N=C3N)...
4,3909,SMI_14356,0.8563,C1COCCN1C2=CC=C(C=C2)NC3=NC=CC(=N3)C4=CC=C(C=C...
...,...,...,...,...
23657,3628,SMI_6419,0.7655,C1=CC2=C(C=CN=C2)C(=C1)S(=O)(=O)NCCNCC=CC3=CC=...
23658,3628,SMI_659,0.6784,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...
23659,3628,SMI_7473,0.8419,C1CC1NS(=O)(=O)C2=CC(=C(C=C2)C3=CSC=C3)NC(=O)N...
23660,3628,SMI_7971,0.8043,CC1=C(NC(=C1C(=O)N2CCCC2CN3CCCC3)C)C=C4C5=C(C=...
23661,3628,SMI_8098,0.5327,CC1=C(SC2=C1C(=NC(C3=NN=C(N32)C)CC(=O)NC4=CC=C...

In [7]:
# Convert SMILES to Morgan fingerprints
def smiles_to_fingerprint(smiles):
    mol = Chem.MolFromSmiles(smiles)
    fingerprint = AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=1024)  # Adjust radius and nBits as needed
    fingerprint_array = np.array(fingerprint)
    return fingerprint_array

# smiles_to_fingerprint(merged_df.isoSMILES[0])
# # Apply the function to your SMILES column
merged_df['fingerprint'] = merged_df['canSMILES'].apply(smiles_to_fingerprint)

fingerprint_map = merged_df[['fingerprint',"improve_drug_id"]]
merged_df = merged_df[["improve_sample_id","improve_drug_id","dose_response_value"]]
merged_df

       improve_sample_id improve_drug_id  dose_response_value
0                   3909       SMI_11493               0.4916
1                   3909       SMI_11502               0.8310
2                   3909       SMI_11509               0.3593
3                   3909       SMI_13100               0.7340
4                   3909       SMI_14356               0.8563
...                  ...             ...                  ...
23657               3628        SMI_6419               0.7655
23658               3628         SMI_659               0.6784
23659               3628        SMI_7473               0.8419
23660               3628        SMI_7971               0.8043
23661               3628        SMI_8098               0.5327

[23662 rows x 3 columns]

In [8]:
fingerprint_map

                                             fingerprint improve_drug_id
0      [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...       SMI_11493
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...       SMI_11502
2      [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...       SMI_11509
3      [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...       SMI_13100
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...       SMI_14356
...                                                  ...             ...
23657  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...        SMI_6419
23658  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         SMI_659
23659  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, ...        SMI_7473
23660  [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...        SMI_7971
23661  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...        SMI_8098

[23662 rows x 2 columns]

In [9]:
fingerprint_dict = fingerprint_map.set_index('improve_drug_id')['fingerprint'].to_dict()
fingerprint_dict

{'SMI_11493': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_11502': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_11509': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_13100': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_14356': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_16810': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_18303': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_18541': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_19449': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_20505': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_23048': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_24635': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_25125': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_28228': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_31077': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_3109': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_34232': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_3871': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_39432': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_3962': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_41466': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_41952': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_44394': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_44535': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_46879': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_4862': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_5060': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_5108': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_51801': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_53126': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_53245': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_54944': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_55461': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_55588': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_55592': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_55606': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_55628': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_55656': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_55905': array([0, 0, 1, ..., 0, 0, 0]),
 'SMI_56397': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_56545': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56574': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_56575': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56577': array([0, 0, 1, ..., 0, 0, 0]),
 'SMI_56579': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56581': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56583': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56584': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56587': array([0, 0, 0, ..., 1, 0, 0]),
 'SMI_56592': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56594': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56595': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56597': array([0, 0, 1, ..., 0, 0, 0]),
 'SMI_6419': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_7971': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_8294': array([0, 0, 0, ..., 1, 0, 0]),
 'SMI_10376': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_12992': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_14902': array([1, 0, 0, ..., 0, 0, 0]),
 'SMI_20869': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_32681': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_35323': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_35928': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_41335': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_46123': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_51900': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_52919': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_5476': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56093': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56138': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56270': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56576': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_56586': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56596': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_10197': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_10282': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_13815': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_18301': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_19534': array([0, 0, 1, ..., 0, 0, 0]),
 'SMI_32922': array([0, 1, 1, ..., 0, 0, 0]),
 'SMI_33555': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_40111': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_40153': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_40233': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_43282': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_52219': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_53250': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_55630': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_55995': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56560': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_56590': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_659': array([0, 0, 0, ..., 0, 1, 0]),
 'SMI_7473': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_20022': array([0, 0, 1, ..., 0, 0, 0]),
 'SMI_39390': array([1, 0, 0, ..., 0, 0, 0]),
 'SMI_39631': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_8098': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56593': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_23119': array([1, 1, 0, ..., 0, 0, 0]),
 'SMI_56573': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_50850': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_5287': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_46990': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_5537': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_39543': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56589': array([0, 1, 0, ..., 0, 0, 0]),
 'SMI_55577': array([0, 0, 0, ..., 0, 0, 0]),
 'SMI_56580': array([0, 0, 0, ..., 0, 0, 0])}

In [10]:
beataml.transcriptomics

          improve_sample_id  transcriptomics  entrez_id   source    study
0                      3379         0.663065       7105  synapse  BeatAML
1                      3379         0.000000      64102  synapse  BeatAML
2                      3379        32.826879       8813  synapse  BeatAML
3                      3379         4.388498      57147  synapse  BeatAML
4                      3379         1.193071      55732  synapse  BeatAML
...                     ...              ...        ...      ...      ...
20036591               3965         1.135523          0  synapse  BeatAML
20036592               3965         9.591371          0  synapse  BeatAML
20036593               3965         0.322676          0  synapse  BeatAML
20036594               3965         6.711485          0  synapse  BeatAML
20036595               3965         0.041147          0  synapse  BeatAML

[20036596 rows x 5 columns]

In [14]:
def extract_sample_info(ref_df: pd.DataFrame, index_ref: dict, info_name: str, sample_id: str, mean_values: list, std_values: list, mean_fill:int=0, std_fill:int=0.0001) -> None:
    cands = ref_df[(ref_df["improve_sample_id"]==sample_id)]
    for entrez in cands["entrez_id"].unique().tolist():
        values = ref_df[(ref_df["entrez_id"]==entrez)][info_name].values
        if values.size==0:
            mean_values[index_ref[entrez]] = mean_fill
            std_values[index_ref[entrez]] = std_fill
        else:
            mean_values[index_ref[entrez]] = np.mean(values)
            std_values[index_ref[entrez]] = max(np.std(values), std_fill)

In [ ]:
final_data = []
unique_entrez_ids = list(set(beataml.proteomics.entrez_id.unique()).union(set(beataml.transcriptomics.entrez_id.unique())))
entrez_length = len(unique_entrez_ids)
print(f"info dimension {entrez_length}")
entrez_lookup = {element: index for index, element in enumerate(unique_entrez_ids)}

count = 0
for improve_sample_id, improve_drug_id, dose_response_value in zip(merged_df["improve_sample_id"], merged_df["improve_drug_id"], merged_df["dose_response_value"]):
    transcriptomics_mean = [None]*entrez_length
    transcriptomics_std = [None]*entrez_length
    proteomics_mean = [None]*entrez_length
    proteomics_std = [None]*entrez_length
    extract_sample_info(beataml.transcriptomics, entrez_lookup, "transcriptomics", improve_sample_id, transcriptomics_mean, transcriptomics_std)
    extract_sample_info(beataml.proteomics, entrez_lookup, "proteomics", improve_sample_id, proteomics_mean, proteomics_std)
    final_data.append([dose_response_value, transcriptomics_mean, transcriptomics_std, proteomics_mean, proteomics_std, improve_sample_id, improve_drug_id])
    count += 1
    if (count % 1000 == 0):
        print(f"finish {count} entries")
aggregated_df = pd.DataFrame(final_data, columns=['dose_response_value', 'transcriptomics_mean', 'transcriptomics_std', 'proteomics_mean', 'proteomics_std', 'improve_sample_id', "improve_drug_id"])
aggregated_df

info dimension 19208

In [ ]:
aggregated_df['fingerprint'] = aggregated_df['improve_drug_id'].map(fingerprint_dict)
aggregated_df = aggregated_df[["dose_response_value","transcriptomics","proteomics","fingerprint"]]

In [11]:
# # Merge merged_df with transcriptomics_df based on improve_sample_id
# tp = pd.merge(beataml.transcriptomics,
#                      beataml.proteomics[['improve_sample_id', 'proteomics', 'entrez_id']],
#                      on=['improve_sample_id','entrez_id'],
#                      how='inner').drop_duplicates()

# merged_df = pd.merge(merged_df,
#                      tp[['improve_sample_id', 'transcriptomics','proteomics', 'entrez_id']],
#                      on='improve_sample_id',
#                      how='inner').drop_duplicates()

In [11]:
# import dask.dataframe as dd

# ddf1 = dd.from_pandas(beataml.transcriptomics[['improve_sample_id', 'transcriptomics', 'entrez_id']], npartitions=1000)
# ddf2 = dd.from_pandas(beataml.proteomics[['improve_sample_id', 'proteomics', 'entrez_id']], npartitions=1000)
# ddf3 = dd.from_pandas(merged_df, npartitions=1000)

# tp_ddf = ddf1.merge(ddf2, on=['improve_sample_id','entrez_id'], how="inner").drop_duplicates()
# merged_ddf = ddf3.merge(tp_ddf[['improve_sample_id', 'transcriptomics','proteomics', 'entrez_id']], on='improve_sample_id', how="inner").drop_duplicates()

In [12]:
# #Create A Hashmap of {improve_sample_id: {improve_drug_id: { entrez_id: transcriptomics, proteomics, auc]}}

# data_dict = {}
# t_mean_fill = 0
# t_std_fill = 0.0001
# p_mean_fill = 0
# p_std_fill = 0.0001
# # Iterate over the DataFrame rows to populate the nested dictionary
# for index, row in merged_df.iterrows():
#     improve_sample_id = row['improve_sample_id']
#     improve_drug_id = row['improve_drug_id']
#     auc = row['dose_response_value']

#     # Initialize improve_sample_id key if not present
#     if improve_sample_id not in data_dict:
#         data_dict[improve_sample_id] = {}
#     # Initialize improve_drug_id key if not present
#     if improve_drug_id not in data_dict[improve_sample_id]:
#         data_dict[improve_sample_id][improve_drug_id] = {}
        
#     entrez_id_t = set(beataml.transcriptomics[beataml.transcriptomics["improve_sample_id"]==improve_sample_id]["entrez_id"].unique().tolist())
#     entrez_id_p = set(beataml.proteomics[beataml.proteomics["improve_sample_id"]==improve_sample_id]["entrez_id"].unique().tolist())
#     entrez_ids = list(entrez_id_t.union(entrez_id_p))
#     for entrez_id in entrez_ids:
#         data_dict[improve_sample_id][improve_drug_id][entrez_id] = {
#             'transcriptomics': list,
#             'proteomics': list,
#             'auc': auc
#         }
#         transcriptomics = beataml.transcriptomics[(beataml.transcriptomics["entrez_id"]==entrez_id) & (beataml.transcriptomics["improve_sample_id"]==improve_sample_id)]["transcriptomics"].values
#         if transcriptomics.size == 0:
#             transcriptomics_mean = t_mean_fill
#             transcriptomics_std = t_std_fill
#         else:
#             transcriptomics_mean = np.mean(transcriptomics).item()
#             transcriptomics_std = max(t_std_fill, np.std(transcriptomics).item())
#         proteomics = beataml.proteomics[(beataml.proteomics["entrez_id"]==entrez_id) & (beataml.proteomics["improve_sample_id"]==improve_sample_id)]["proteomics"].values
#         if proteomics.size == 0:
#             proteomics_mean = p_mean_fill
#             proteomics_std = p_std_fill
#         else:
#             proteomics_mean = np.mean(proteomics).item()
#             proteomics_std = max(p_std_fill, np.std(proteomics).item())      
#         data_dict[improve_sample_id][improve_drug_id][entrez_id]['transcriptomics'] = [transcriptomics_mean, transcriptomics_std]
#         data_dict[improve_sample_id][improve_drug_id][entrez_id]['proteomics'] = [proteomics_mean, proteomics_std]

In [ ]:
# unique_entrez_ids = set(beataml.proteomics.entrez_id.unique()).union(set(beataml.transcriptomics.entrez_id.unique()))

# # # Construct the final DataFrame
# final_data = []
# for improve_sample_id, sample_id_data in data_dict.items():
#     for improve_drug_id, drug_id_data in sample_id_data.items():
#         transcriptomics_mean = []
#         transcriptomics_std = []
#         proteomics_mean = []
#         proteomics_std = []
#         for entrez_id in unique_entrez_ids:
#             if entrez_id in drug_id_data:
#                 transcriptomics.append(drug_id_data[entrez_id]['transcriptomics'])
#                 proteomics.append(drug_id_data[entrez_id]['proteomics'])
#                 transcriptomics_mean.append(drug_id_data[entrez_id]['transcriptomics'][0])
#                 transcriptomics_std.append(drug_id_data[entrez_id]['transcriptomics'][1])
#                 proteomics_mean.append(drug_id_data[entrez_id]['proteomics'][0])
#                 proteomics_std.append(drug_id_data[entrez_id]['proteomics'][1])
#                 auc = drug_id_data[entrez_id]['auc']
#         final_data.append([auc, transcriptomics_mean, transcriptomics_std, proteomics_mean, proteomics_std, improve_sample_id, improve_drug_id])

# # # Create the DataFrame
# aggregated_df = pd.DataFrame(final_data, columns=['auc', 'transcriptomics_mean', 'transcriptomics_std', 'proteomics_mean', 'proteomics_std', 'improve_sample_id', "improve_drug_id"])
# aggregated_df

In [ ]:
# # Map in the fingerprint by improve_drug_id. Remove improve_drug_id.
# aggregated_df['fingerprint'] = aggregated_df['improve_drug_id'].map(fingerprint_dict)
# aggregated_df = aggregated_df[["auc","transcriptomics","proteomics","fingerprint"]]